### ISSUE TITLE
 --without-gossip on worker throws error

### ISSUE THREAD

**Issue by sumitasok** [sumitasok/celery#5]
```
add_task_1   | [2020-02-14 07:56:00,681: ERROR/MainProcess] pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")
add_task_1   | Traceback (most recent call last):
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 104, in dispatch
add_task_1   |     reply = handle(method, arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 126, in handle_cast
add_task_1   |     return self.handle(method, arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 120, in handle
add_task_1   |     return self.handlers[method](self.state, **arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/celery/worker/control.py", line 279, in enable_events
add_task_1   |     if dispatcher.groups and 'task' not in dispatcher.groups:
add_task_1   | AttributeError: 'NoneType' object has no attribute 'groups'
xsum_task_1  | [2020-02-14 07:56:05,625: ERROR/MainProcess] pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")
xsum_task_1  | Traceback (most recent call last):
xsum_task_1  |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 104, in dispatch
xsum_task_1  |     reply = handle(method, arguments)
xsum_task_1  |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 126, in handle_cast
xsum_task_1  |     return self.handle(method, arguments)
xsum_task_1  |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 120, in handle
xsum_task_1  |     return self.handlers[method](self.state, **arguments)
xsum_task_1  |   File "/usr/local/lib/python3.8/site-packages/celery/worker/control.py", line 279, in enable_events
xsum_task_1  |     if dispatcher.groups and 'task' not in dispatcher.groups:
xsum_task_1  | AttributeError: 'NoneType' object has no attribute 'groups'
add_task_1   | [2020-02-14 07:56:05,630: ERROR/MainProcess] pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")
add_task_1   | Traceback (most recent call last):
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 104, in dispatch
add_task_1   |     reply = handle(method, arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 126, in handle_cast
add_task_1   |     return self.handle(method, arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 120, in handle
add_task_1   |     return self.handlers[method](self.state, **arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/celery/worker/control.py", line 279, in enable_events
add_task_1   |     if dispatcher.groups and 'task' not in dispatcher.groups:
add_task_1   | AttributeError: 'NoneType' object has no attribute 'groups'
add_task_1   | [2020-02-14 07:56:10,642: ERROR/MainProcess] pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")
add_task_1   | Traceback (most recent call last):
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 104, in dispatch
add_task_1   |     reply = handle(method, arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 126, in handle_cast
add_task_1   |     return self.handle(method, arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 120, in handle
add_task_1   |     return self.handlers[method](self.state, **arguments)
add_task_1   |   File "/usr/local/lib/python3.8/site-packages/celery/worker/control.py", line 279, in enable_events
add_task_1   |     if dispatcher.groups and 'task' not in dispatcher.groups:
add_task_1   | AttributeError: 'NoneType' object has no attribute 'groups'
xsum_task_1  | [2020-02-14 07:56:10,642: ERROR/MainProcess] pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")
xsum_task_1  | Traceback (most recent call last):
xsum_task_1  |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 104, in dispatch
xsum_task_1  |     reply = handle(method, arguments)
xsum_task_1  |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 126, in handle_cast
xsum_task_1  |     return self.handle(method, arguments)
xsum_task_1  |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 120, in handle
xsum_task_1  |     return self.handlers[method](self.state, **arguments)
xsum_task_1  |   File "/usr/local/lib/python3.8/site-packages/celery/worker/control.py", line 279, in enable_events
xsum_task_1  |     if dispatcher.groups and 'task' not in dispatcher.groups:
xsum_task_1  | AttributeError: 'NoneType' object has no attribute 'groups'
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by srinivasakartheek** [comment]
@sumitasok Did you figure out the reason for this error?

**Comment by srinivasakartheek** [comment]
Looks like this issue happens when we disable gossip and try to get events using inspect either manually for using flower for example
https://docs.celeryproject.org/en/stable/userguide/monitoring.html#events

**Comment by hishamkaram** [comment]
@srinivasakartheek @sumitasok this issue disappeared when I enabled events for the workers with this flag `-E` or `--task-events` example:
`celery -A project.celery.app worker -E -Q messaging  --loglevel=INFO --autoscale=10,4 --without-heartbeat --without-gossip --without-mingle`
